export const direction = {
  ACROSS: 0,
  DOWN: 1,
};

export const daysOfTheWeek = {
  SUNDAY: 1,
  MONDAY: 2,
  TUESDAY: 4,
  WEDNESDAY: 8,
  THURSDAY: 16,
  FRIDAY: 32,
  SATURDAY: 64,
};

export const puzzleNames = {
  NYT_DAILY: "New York Times Daily",
  LA_TIMES: "LA Times",
  BRAINS_ONLY: "Creators Syndicate",
  UNIVERSAL: "Universal",
  USA_TODAY: "USA Today",
  DAILY_AMERICAN: "Daily American",
  OCP_1: "Online Crosswords #1",
  OCP_2: "Online Crosswords #2",
  OCP_3: "Online Crosswords #3",
  OCP_4: "Online Crosswords #4",
  OCP_5: "Online Crosswords #5",
  OCP_6: "Online Crosswords #6",
  OCP_7: "Online Crosswords #7",
  ARKADIUM: "Arkadium",
  PENNYDELL: "Penny Dell",
  KFSSHEFFER: "Sheffer Daily",
  KFSJOSEPH: "Joseph Daily",
  WSJ: "Wall Street Journal",
  NYTCLASSIC: "New York Times Classic Puzzle 1",
  NYTCLASSIC2: "New York Times Classic Puzzle 2",
  NYTCLASSIC3: "New York Times Classic Puzzle 3",
  BEQ_TUESDAY: "Brendan Emmett Quigley Tuesday",
  JONESIN: "Joensin",
  BEQ_FRIDAY: "Brendan Emmett Quigley Friday",
  KFSPREMIER: "King Features Sunday",
  BOSTON_GLOBE: "Boston Globe",
};

export const puzzleIDs = {
  NYT_DAILY: "NYTD",
  LA_TIMES: "LAT",
  BRAINS_ONLY: "CS",
  UNIVERSAL: "UNI",
  USA_TODAY: "USAT",
  DAILY_AMERICAN: "DA",
  OCP_1: "OC1",
  OCP_2: "OC2",
  OCP_3: "OC3",
  OCP_4: "OC4",
  OCP_5: "OC5",
  OCP_6: "OC6",
  OCP_7: "OC7",
  ARKADIUM: "ARK",
  PENNYDELL: "PD",
  KFSSHEFFER: "SD",
  KFSJOSEPH: "JD",
  WSJ: "WSJ",
  NYTCLASSIC: "NYTC1",
  NYTCLASSIC2: "NYTC2",
  NYTCLASSIC3: "NYTC3",
  BEQ_TUESDAY: "BEQT",
  JONESIN: "J",
  BEQ_FRIDAY: "BEQF",
  KFSPREMIER: "KFS",
  BOSTON_GLOBE: "BG",
};

export const puzzleTypes = {
  ACROSS_LITE: 0,
  UCLICK: 1,
  BRAINSONLY_COM: 2,
  ONLINE_CROSSWORDS: 3,
  KFS: 4,
  WSJ: 5,
  NYT: 6,
};
